import { ILayoutData } from 'types';

const data: ILayoutData = {
  IMAGE_WIDTH_3COLUMNS: 416,
  IMAGE_WIDTH_2COLUMNS: 463,
  IMAGE_WIDTH_1COLUMN: 760,

  COLUMN_HEIGHT: 2600,
  ROW_GAP: 10,
  COLUMN_GAP: 24,

  SCREEN_WIDTH_3COLUMNS: 9999,
  SCREEN_WIDTH_2COLUMNS: 975,
  SCREEN_WIDTH_1COLUMN: 765,

  HEADER_HEIGHT: 62,

  FULL_MODAL_SCREEN_WIDTH: '865px',
};

export default data;
