interface LayoutData {
  IMAGE_WIDTH_3COLUMNS: number;
  IMAGE_WIDTH_2COLUMNS: number;
  IMAGE_WIDTH_1COLUMN: number;

  COLUMN_HEIGHT: number;
  ROW_GAP: number;
  COLUMN_GAP: number;

  SCREEN_WIDTH_3COLUMNS: number;
  SCREEN_WIDTH_2COLUMNS: number;
  SCREEN_WIDTH_1COLUMN: number;

  HEADER_HEIGHT: number;

  FULL_MODAL_SCREEN_WIDTH: string;
}

const data: LayoutData = {
  IMAGE_WIDTH_3COLUMNS: 416,
  IMAGE_WIDTH_2COLUMNS: 463,
  IMAGE_WIDTH_1COLUMN: 760,

  COLUMN_HEIGHT: 2600,
  ROW_GAP: 10,
  COLUMN_GAP: 24,

  SCREEN_WIDTH_3COLUMNS: 9999,
  SCREEN_WIDTH_2COLUMNS: 975,
  SCREEN_WIDTH_1COLUMN: 765,

  HEADER_HEIGHT: 62,

  FULL_MODAL_SCREEN_WIDTH: '865px',
};

export default data;
